---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: store
  namespace: filestore
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
---