---
apiVersion: v1
kind: Service
metadata:
  name: filestore
  namespace: filestore
spec:
  type: ClusterIP
  selector:
    component: filestore
  ports:
    - name: tcp
      port: 9090
      targetPort: 9090
      protocol: TCP
